### ISSUE TITLE
Build Errors: ART: Squashed merge of AOSP master branch through December 

### ISSUE THREAD

**Issue by Eliminater74** [BenzoRom/art#2]
I have used some of your commits on my ROM, and I keep getting the following errors:
The above Commit is the main commit that starts the errors:

`[44/44] bootstrap /home/eliminater74/Builds/rom/pf-8.1/out/soong/.minibootstrap/build.ninja.in
[4/4] cp /home/eliminater74/Builds/rom/pf-8.1/out/soong/.bootstrap/bin/bpglob
[876/877] glob vendor/////*/Android.bp
[54/55] soong_build docs /home/eliminater74/Builds/rom/pf-8.1/out/soong/.bootstrap/docs/soong_build.html
FAILED: /home/eliminater74/Builds/rom/pf-8.1/out/soong/.bootstrap/docs/soong_build.html 
/home/eliminater74/Builds/rom/pf-8.1/out/soong/.bootstrap/bin/soong_build  -t -b /home/eliminater74/Builds/rom/pf-8.1/out/soong --docs /home/eliminater74/Builds/rom/pf-8.1/out/soong/.bootstrap/docs/soong_build.html ./Android.bp
error: art/test/Android.bp:364:1: "libtistress" depends on undefined module "slicer"
error: art/test/Android.bp:370:1: "libtistressd" depends on undefined module "slicer"
[55/55] /home/eliminater74/Builds/rom/pf-8.1/out/soong/.bootstrap/bin/soong_build /home/eliminater74/Builds/rom/pf-8.1/out/soong/build.ninja
FAILED: /home/eliminater74/Builds/rom/pf-8.1/out/soong/build.ninja 
/home/eliminater74/Builds/rom/pf-8.1/out/soong/.bootstrap/bin/soong_build  -t -b /home/eliminater74/Builds/rom/pf-8.1/out/soong -d /home/eliminater74/Builds/rom/pf-8.1/out/soong/build.ninja.d -o /home/eliminater74/Builds/rom/pf-8.1/out/soong/build.ninja Android.bp
error: art/test/Android.bp:370:1: "libtistressd" depends on undefined module "slicer"
error: art/test/Android.bp:364:1: "libtistress" depends on undefined module "slicer"
ninja: build stopped: subcommand failed.
10:01:21 soong failed with: exit status 1`

I have google searched with no luck, I even tried using your full art commits and still same error, I have searched around on your repo, with no luck, can you point me in the right direction that will allow me to fix this issue?

Thanks man..

EDIT: I removed the "SLICER"  lib from the shared libs in test/Android.bp and it went through,
But now I keep getting this error:
`art/disassembler/disassembler_arm.cc:66:40: error: no member named 'GetImmediate' in 'vixl::aarch32::Disassembler::PrintLabel'
          const int32_t offset = label.GetImmediate();`

Any clue?

**Comment by mydongistiny** [comment]
To fix the vixl error you'll either have to grab my external/vixl or revert https://android.googlesource.com/platform/art/+/672b9c1e95beed861a63d4a4c273114387f035a6%5E%21/

You wouldn't need the whole repo though, just this commit:
https://github.com/BenzoRom/external_vixl/commit/d4da0d10cf9591e9c43230e1c37232cb719a954c
